version = 1

[[annotations]]
path = "Cargo.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "Â© GSI Helmholtzzentrum f. Schwerionenforschung GmbH, Darmstadt, Germany"
SPDX-License-Identifier = "LGPL-3.0-or-later"
